/**
 * Content metadata for MDX posts and projects.
 *
 * Data is loaded at build time from:
 * - content/projects.md (YAML frontmatter)
 * - content/writing/*.mdx (YAML frontmatter)
 *
 * The virtual:content module is generated by the contentPlugin in vite.config.ts
 */

import {
  projects as rawProjects,
  posts as rawPosts,
} from "virtual:content";

// =============================================================================
// Post Types and Helpers
// =============================================================================

export interface PostMeta {
  slug: string;
  title: string;
  date: string;
  description: string;
  featured?: boolean;
}

// Type the imports from virtual module
export const posts: PostMeta[] = rawPosts as PostMeta[];

export function getAllPosts(): PostMeta[] {
  return posts.sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );
}

export function getPostBySlug(slug: string): PostMeta | undefined {
  return posts.find((p) => p.slug === slug);
}

/**
 * Check if a blog post exists for a given project slug.
 * Convention: blog posts about projects are named "project-{projectSlug}"
 */
export function getProjectPost(projectSlug: string): PostMeta | undefined {
  return posts.find((p) => p.slug === `project-${projectSlug}`);
}

export function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

// =============================================================================
// Project Types and Helpers
// =============================================================================

export interface ProjectMeta {
  slug: string;
  name: string;
  description: string;
  tech: string[];
  url?: string;
  github?: string;
  featured: boolean;
}

// Type the imports from virtual module
export const projects: ProjectMeta[] = rawProjects as ProjectMeta[];

export function getAllProjects(): ProjectMeta[] {
  return projects;
}

export function getFeaturedProjects(): ProjectMeta[] {
  return projects.filter((p) => p.featured);
}

export function getOtherProjects(): ProjectMeta[] {
  return projects.filter((p) => !p.featured);
}

export function getProjectBySlug(slug: string): ProjectMeta | undefined {
  return projects.find((p) => p.slug === slug);
}

// =============================================================================
// Searchable Content (for RAG/Vectorize)
// =============================================================================

export interface SearchableContent {
  id: string;
  type: "post" | "project";
  title: string;
  description: string;
  url: string;
}

export function getAllSearchableContent(): SearchableContent[] {
  const postContent: SearchableContent[] = posts.map((post) => ({
    id: `post-${post.slug}`,
    type: "post",
    title: post.title,
    description: post.description,
    url: `/writing/${post.slug}`,
  }));

  const projectContent: SearchableContent[] = projects.map((project) => ({
    id: `project-${project.slug}`,
    type: "project",
    title: project.name,
    description: `${project.description} Technologies: ${project.tech.join(", ")}`,
    url: project.url || project.github || `/projects`,
  }));

  return [...postContent, ...projectContent];
}
