// Fallback data for when the database is unavailable or empty
// This ensures the site renders properly during development and initial setup

export const fallbackPosts = [
  {
    id: "1",
    slug: "the-rule-of-three",
    title: "The Rule of Three",
    excerpt: "Comparing React Router v7, TanStack Start, and Next.js. What I learned building the same app three times.",
    content: "",
    contentHtml: null,
    publishedAt: new Date("2025-02-01"),
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-01"),
    authorId: "1",
    featured: true,
    readTime: 8,
    views: 0,
    status: "published" as const,
  },
  {
    id: "2",
    slug: "prisma-in-2025",
    title: "Why I Still Choose Prisma",
    excerpt: "Despite the alternatives, Prisma remains my go-to ORM. Here's why type safety and DX still win.",
    content: "",
    contentHtml: null,
    publishedAt: new Date("2025-01-15"),
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-15"),
    authorId: "1",
    featured: true,
    readTime: 6,
    views: 0,
    status: "published" as const,
  },
  {
    id: "3",
    slug: "scaling-teams",
    title: "Scaling Engineering Teams",
    excerpt: "Lessons from growing an engineering organization from 5 to 40+ people. What worked, what didn't.",
    content: "",
    contentHtml: null,
    publishedAt: new Date("2024-12-20"),
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-20"),
    authorId: "1",
    featured: true,
    readTime: 12,
    views: 0,
    status: "published" as const,
  },
  {
    id: "4",
    slug: "ai-coding-assistants",
    title: "Living with AI Coding Assistants",
    excerpt: "How I use Cursor, Claude, and Copilot in my daily workflow. The good, the bad, and the surprising.",
    content: "",
    contentHtml: null,
    publishedAt: new Date("2024-11-10"),
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-11-10"),
    authorId: "1",
    featured: false,
    readTime: 10,
    views: 0,
    status: "published" as const,
  },
];

export const fallbackProjects = [
  {
    id: "1",
    name: "Yogan Hockey",
    slug: "yogan-hockey",
    description: "Real-time NHL stats app built with Phoenix LiveView. Uses ETS for incremental static regeneration, outperforming Next.js in speed tests.",
    longDescription: null,
    url: "https://yogan-hockey.fly.dev",
    githubUrl: "https://github.com/ryanyogan/yogan-hockey",
    imageUrl: null,
    featured: true,
    stars: 45,
    forks: 5,
    language: "Elixir",
    topics: ["Elixir", "Phoenix", "LiveView", "Tailwind"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
    lastActivityAt: new Date("2024-12-01"),
  },
  {
    id: "2",
    name: "10.yogan.dev",
    slug: "10-yogan-dev",
    description: "Westworld-themed Valentine's Day experience with immersive animations, custom cursors, and cinematic transitions.",
    longDescription: null,
    url: "https://10.yogan.dev",
    githubUrl: "https://github.com/ryanyogan/10-year",
    imageUrl: null,
    featured: true,
    stars: 12,
    forks: 2,
    language: "TypeScript",
    topics: ["React", "GSAP", "Framer Motion", "Design"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-14"),
    lastActivityAt: new Date("2024-02-14"),
  },
  {
    id: "3",
    name: "Ice Yeti",
    slug: "ice-yeti",
    description: "Hockey social network for players, coaches, and fans. Team management, game scheduling, and stats tracking.",
    longDescription: null,
    url: "https://slax.yogan.dev",
    githubUrl: null,
    imageUrl: null,
    featured: true,
    stars: 0,
    forks: 0,
    language: "Elixir",
    topics: ["Elixir", "Phoenix", "LiveView", "PostgreSQL"],
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-11-01"),
    lastActivityAt: new Date("2024-11-01"),
  },
  {
    id: "4",
    name: "ryanyogan.com",
    slug: "ryanyogan-com",
    description: "AI-powered personal website with TanStack Start on Cloudflare Workers.",
    longDescription: null,
    url: "https://ryanyogan.com",
    githubUrl: "https://github.com/ryanyogan/ryanyogan.com",
    imageUrl: null,
    featured: false,
    stars: 0,
    forks: 0,
    language: "TypeScript",
    topics: ["TanStack Start", "Cloudflare", "Workers AI"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-02-01"),
    lastActivityAt: new Date("2025-02-01"),
  },
  {
    id: "5",
    name: "Embedded Training System",
    slug: "embedded-training",
    description: "Ice training equipment with embedded sensors. Hardware meets software for athlete performance tracking.",
    longDescription: null,
    url: null,
    githubUrl: null,
    imageUrl: null,
    featured: false,
    stars: 0,
    forks: 0,
    language: "Rust",
    topics: ["Embedded", "Rust", "IoT", "Hardware"],
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-12-01"),
    lastActivityAt: new Date("2024-12-01"),
  },
];

export const fallbackExperiences = [
  {
    id: "1",
    company: "Procore Technologies",
    title: "Staff Engineer / Engineering Manager",
    location: "Chicago, IL (Remote)",
    startDate: new Date("2018-01-01"),
    endDate: new Date("2024-06-01"),
    current: false,
    description: "Pre-IPO construction tech. Led platform initiatives and engineering teams. Built real-time systems serving millions of construction professionals worldwide.",
    highlights: [
      "Led critical platform initiatives through IPO",
      "Grew and mentored engineering teams",
      "Built real-time collaboration systems at scale",
    ],
    technologies: ["Ruby", "Rails", "React", "GraphQL", "PostgreSQL"],
    linkedinUrl: null,
    order: 1,
  },
  {
    id: "2",
    company: "Peak6 Investments",
    title: "Senior Software Engineer",
    location: "Chicago, IL",
    startDate: new Date("2015-03-01"),
    endDate: new Date("2017-12-01"),
    current: false,
    description: "High-frequency trading firm. Built low-latency trading systems and real-time market data infrastructure. Performance-critical software where milliseconds matter.",
    highlights: [
      "Built low-latency trading systems",
      "Real-time market data processing",
      "Performance optimization at microsecond level",
    ],
    technologies: ["Java", "C++", "Python", "Kafka", "Redis"],
    linkedinUrl: null,
    order: 2,
  },
  {
    id: "3",
    company: "Startups (Various)",
    title: "Founding Engineer → Engineering Lead",
    location: "Chicago / Remote",
    startDate: new Date("2005-01-01"),
    endDate: new Date("2015-02-01"),
    current: false,
    description: "Multiple startup experiences. Built products from zero to scale. Grew engineering teams from 0 to 40+ people. Full-stack development across web and mobile.",
    highlights: [
      "Built and scaled multiple products from scratch",
      "Grew teams from 0 to 40+ engineers",
      "Full-stack across web, mobile, and infrastructure",
    ],
    technologies: ["Ruby", "Python", "JavaScript", "PostgreSQL", "AWS"],
    linkedinUrl: null,
    order: 3,
  },
];

export const fallbackSkills = [
  // Languages
  { id: "1", name: "TypeScript", category: "language" as const, proficiency: 95, yearsExperience: 8, featured: true },
  { id: "2", name: "Elixir", category: "language" as const, proficiency: 85, yearsExperience: 4, featured: true },
  { id: "3", name: "Go", category: "language" as const, proficiency: 75, yearsExperience: 3, featured: true },
  { id: "4", name: "Ruby", category: "language" as const, proficiency: 90, yearsExperience: 12, featured: true },
  { id: "5", name: "Rust", category: "language" as const, proficiency: 60, yearsExperience: 2, featured: true },
  // Frontend
  { id: "6", name: "React", category: "frontend" as const, proficiency: 95, yearsExperience: 8, featured: true },
  { id: "7", name: "TanStack", category: "frontend" as const, proficiency: 85, yearsExperience: 2, featured: true },
  { id: "8", name: "Next.js", category: "frontend" as const, proficiency: 90, yearsExperience: 5, featured: true },
  { id: "9", name: "Phoenix LiveView", category: "frontend" as const, proficiency: 80, yearsExperience: 3, featured: true },
  // Backend
  { id: "10", name: "Node.js", category: "backend" as const, proficiency: 90, yearsExperience: 10, featured: true },
  { id: "11", name: "Phoenix", category: "backend" as const, proficiency: 85, yearsExperience: 4, featured: true },
  { id: "12", name: "Rails", category: "backend" as const, proficiency: 90, yearsExperience: 12, featured: true },
  { id: "13", name: "GraphQL", category: "backend" as const, proficiency: 85, yearsExperience: 6, featured: true },
  // Infrastructure
  { id: "14", name: "Cloudflare", category: "devops" as const, proficiency: 80, yearsExperience: 3, featured: true },
  { id: "15", name: "AWS", category: "devops" as const, proficiency: 85, yearsExperience: 10, featured: true },
  { id: "16", name: "Docker", category: "devops" as const, proficiency: 85, yearsExperience: 8, featured: true },
  { id: "17", name: "Kubernetes", category: "devops" as const, proficiency: 75, yearsExperience: 5, featured: true },
  // Leadership
  { id: "18", name: "Team Building", category: "leadership" as const, proficiency: 90, yearsExperience: 10, featured: true },
  { id: "19", name: "Technical Strategy", category: "leadership" as const, proficiency: 85, yearsExperience: 8, featured: true },
  { id: "20", name: "Mentorship", category: "leadership" as const, proficiency: 90, yearsExperience: 10, featured: true },
];
