/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as ApiTriggerWorkflowRouteImport } from './routes/api/trigger-workflow'
import { Route as ApiSeedVectorizeRouteImport } from './routes/api/seed-vectorize'
import { Route as ApiSeedSearchRouteImport } from './routes/api/seed-search'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiGeneratePostRouteImport } from './routes/api/generate-post'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminExperienceRouteImport } from './routes/admin/experience'
import { Route as AdminContentRouteImport } from './routes/admin/content'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTriggerWorkflowRoute = ApiTriggerWorkflowRouteImport.update({
  id: '/api/trigger-workflow',
  path: '/api/trigger-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedVectorizeRoute = ApiSeedVectorizeRouteImport.update({
  id: '/api/seed-vectorize',
  path: '/api/seed-vectorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedSearchRoute = ApiSeedSearchRouteImport.update({
  id: '/api/seed-search',
  path: '/api/seed-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePostRoute = ApiGeneratePostRouteImport.update({
  id: '/api/generate-post',
  path: '/api/generate-post',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExperienceRoute = AdminExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/work': typeof WorkRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/generate-post': typeof ApiGeneratePostRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seed-search': typeof ApiSeedSearchRoute
  '/api/seed-vectorize': typeof ApiSeedVectorizeRoute
  '/api/trigger-workflow': typeof ApiTriggerWorkflowRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/work': typeof WorkRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/generate-post': typeof ApiGeneratePostRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seed-search': typeof ApiSeedSearchRoute
  '/api/seed-vectorize': typeof ApiSeedVectorizeRoute
  '/api/trigger-workflow': typeof ApiTriggerWorkflowRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin': typeof AdminIndexRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/work': typeof WorkRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/generate-post': typeof ApiGeneratePostRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seed-search': typeof ApiSeedSearchRoute
  '/api/seed-vectorize': typeof ApiSeedVectorizeRoute
  '/api/trigger-workflow': typeof ApiTriggerWorkflowRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/projects'
    | '/work'
    | '/admin/content'
    | '/admin/experience'
    | '/admin/projects'
    | '/api/generate-post'
    | '/api/search'
    | '/api/seed-search'
    | '/api/seed-vectorize'
    | '/api/trigger-workflow'
    | '/writing/$slug'
    | '/admin/'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/work'
    | '/admin/content'
    | '/admin/experience'
    | '/admin/projects'
    | '/api/generate-post'
    | '/api/search'
    | '/api/seed-search'
    | '/api/seed-vectorize'
    | '/api/trigger-workflow'
    | '/writing/$slug'
    | '/admin'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/projects'
    | '/work'
    | '/admin/content'
    | '/admin/experience'
    | '/admin/projects'
    | '/api/generate-post'
    | '/api/search'
    | '/api/seed-search'
    | '/api/seed-vectorize'
    | '/api/trigger-workflow'
    | '/writing/$slug'
    | '/admin/'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  WorkRoute: typeof WorkRoute
  ApiGeneratePostRoute: typeof ApiGeneratePostRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSeedSearchRoute: typeof ApiSeedSearchRoute
  ApiSeedVectorizeRoute: typeof ApiSeedVectorizeRoute
  ApiTriggerWorkflowRoute: typeof ApiTriggerWorkflowRoute
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trigger-workflow': {
      id: '/api/trigger-workflow'
      path: '/api/trigger-workflow'
      fullPath: '/api/trigger-workflow'
      preLoaderRoute: typeof ApiTriggerWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-vectorize': {
      id: '/api/seed-vectorize'
      path: '/api/seed-vectorize'
      fullPath: '/api/seed-vectorize'
      preLoaderRoute: typeof ApiSeedVectorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-search': {
      id: '/api/seed-search'
      path: '/api/seed-search'
      fullPath: '/api/seed-search'
      preLoaderRoute: typeof ApiSeedSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-post': {
      id: '/api/generate-post'
      path: '/api/generate-post'
      fullPath: '/api/generate-post'
      preLoaderRoute: typeof ApiGeneratePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/experience': {
      id: '/admin/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminExperienceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminExperienceRoute: typeof AdminExperienceRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminExperienceRoute: AdminExperienceRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  WorkRoute: WorkRoute,
  ApiGeneratePostRoute: ApiGeneratePostRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSeedSearchRoute: ApiSeedSearchRoute,
  ApiSeedVectorizeRoute: ApiSeedVectorizeRoute,
  ApiTriggerWorkflowRoute: ApiTriggerWorkflowRoute,
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
