/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as HireRouteImport } from './routes/hire'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as TutorialsIndexRouteImport } from './routes/tutorials/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as ApiSeedSearchRouteImport } from './routes/api/seed-search'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminExperienceRouteImport } from './routes/admin/experience'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as TutorialsCourseSlugIndexRouteImport } from './routes/tutorials/$courseSlug/index'
import { Route as AdminTutorialsIndexRouteImport } from './routes/admin/tutorials/index'
import { Route as TutorialsCourseSlugLessonSlugRouteImport } from './routes/tutorials/$courseSlug/$lessonSlug'
import { Route as AdminTutorialsCourseIdRouteImport } from './routes/admin/tutorials/$courseId'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsIndexRoute = TutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedSearchRoute = ApiSeedSearchRouteImport.update({
  id: '/api/seed-search',
  path: '/api/seed-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExperienceRoute = AdminExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TutorialsCourseSlugIndexRoute =
  TutorialsCourseSlugIndexRouteImport.update({
    id: '/tutorials/$courseSlug/',
    path: '/tutorials/$courseSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTutorialsIndexRoute = AdminTutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TutorialsCourseSlugLessonSlugRoute =
  TutorialsCourseSlugLessonSlugRouteImport.update({
    id: '/tutorials/$courseSlug/$lessonSlug',
    path: '/tutorials/$courseSlug/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTutorialsCourseIdRoute = AdminTutorialsCourseIdRouteImport.update({
  id: '/tutorials/$courseId',
  path: '/tutorials/$courseId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/hire': typeof HireRoute
  '/work': typeof WorkRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seed-search': typeof ApiSeedSearchRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tutorials/': typeof TutorialsIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/admin/tutorials/$courseId': typeof AdminTutorialsCourseIdRoute
  '/tutorials/$courseSlug/$lessonSlug': typeof TutorialsCourseSlugLessonSlugRoute
  '/admin/tutorials/': typeof AdminTutorialsIndexRoute
  '/tutorials/$courseSlug/': typeof TutorialsCourseSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hire': typeof HireRoute
  '/work': typeof WorkRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seed-search': typeof ApiSeedSearchRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/tutorials': typeof TutorialsIndexRoute
  '/writing': typeof WritingIndexRoute
  '/admin/tutorials/$courseId': typeof AdminTutorialsCourseIdRoute
  '/tutorials/$courseSlug/$lessonSlug': typeof TutorialsCourseSlugLessonSlugRoute
  '/admin/tutorials': typeof AdminTutorialsIndexRoute
  '/tutorials/$courseSlug': typeof TutorialsCourseSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/hire': typeof HireRoute
  '/work': typeof WorkRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/seed-search': typeof ApiSeedSearchRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tutorials/': typeof TutorialsIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/admin/tutorials/$courseId': typeof AdminTutorialsCourseIdRoute
  '/tutorials/$courseSlug/$lessonSlug': typeof TutorialsCourseSlugLessonSlugRoute
  '/admin/tutorials/': typeof AdminTutorialsIndexRoute
  '/tutorials/$courseSlug/': typeof TutorialsCourseSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hire'
    | '/work'
    | '/admin/content'
    | '/admin/experience'
    | '/admin/projects'
    | '/api/search'
    | '/api/seed-search'
    | '/api/sitemap'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/admin/'
    | '/projects/'
    | '/tutorials/'
    | '/writing/'
    | '/admin/tutorials/$courseId'
    | '/tutorials/$courseSlug/$lessonSlug'
    | '/admin/tutorials/'
    | '/tutorials/$courseSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hire'
    | '/work'
    | '/admin/content'
    | '/admin/experience'
    | '/admin/projects'
    | '/api/search'
    | '/api/seed-search'
    | '/api/sitemap'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/admin'
    | '/projects'
    | '/tutorials'
    | '/writing'
    | '/admin/tutorials/$courseId'
    | '/tutorials/$courseSlug/$lessonSlug'
    | '/admin/tutorials'
    | '/tutorials/$courseSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/hire'
    | '/work'
    | '/admin/content'
    | '/admin/experience'
    | '/admin/projects'
    | '/api/search'
    | '/api/seed-search'
    | '/api/sitemap'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/admin/'
    | '/projects/'
    | '/tutorials/'
    | '/writing/'
    | '/admin/tutorials/$courseId'
    | '/tutorials/$courseSlug/$lessonSlug'
    | '/admin/tutorials/'
    | '/tutorials/$courseSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  HireRoute: typeof HireRoute
  WorkRoute: typeof WorkRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSeedSearchRoute: typeof ApiSeedSearchRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TutorialsIndexRoute: typeof TutorialsIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
  TutorialsCourseSlugLessonSlugRoute: typeof TutorialsCourseSlugLessonSlugRoute
  TutorialsCourseSlugIndexRoute: typeof TutorialsCourseSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/': {
      id: '/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials/'
      preLoaderRoute: typeof TutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-search': {
      id: '/api/seed-search'
      path: '/api/seed-search'
      fullPath: '/api/seed-search'
      preLoaderRoute: typeof ApiSeedSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/experience': {
      id: '/admin/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminExperienceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/tutorials/$courseSlug/': {
      id: '/tutorials/$courseSlug/'
      path: '/tutorials/$courseSlug'
      fullPath: '/tutorials/$courseSlug/'
      preLoaderRoute: typeof TutorialsCourseSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutorials/': {
      id: '/admin/tutorials/'
      path: '/tutorials'
      fullPath: '/admin/tutorials/'
      preLoaderRoute: typeof AdminTutorialsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/tutorials/$courseSlug/$lessonSlug': {
      id: '/tutorials/$courseSlug/$lessonSlug'
      path: '/tutorials/$courseSlug/$lessonSlug'
      fullPath: '/tutorials/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof TutorialsCourseSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutorials/$courseId': {
      id: '/admin/tutorials/$courseId'
      path: '/tutorials/$courseId'
      fullPath: '/admin/tutorials/$courseId'
      preLoaderRoute: typeof AdminTutorialsCourseIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminExperienceRoute: typeof AdminExperienceRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTutorialsCourseIdRoute: typeof AdminTutorialsCourseIdRoute
  AdminTutorialsIndexRoute: typeof AdminTutorialsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminExperienceRoute: AdminExperienceRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTutorialsCourseIdRoute: AdminTutorialsCourseIdRoute,
  AdminTutorialsIndexRoute: AdminTutorialsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  HireRoute: HireRoute,
  WorkRoute: WorkRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSeedSearchRoute: ApiSeedSearchRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TutorialsIndexRoute: TutorialsIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
  TutorialsCourseSlugLessonSlugRoute: TutorialsCourseSlugLessonSlugRoute,
  TutorialsCourseSlugIndexRoute: TutorialsCourseSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
