/// <reference types="vite/client" />

/**
 * Virtual module for content loaded at build time.
 * Generated by contentPlugin in vite.config.ts
 */
declare module "virtual:content" {
  export const projects: Array<{
    slug: string;
    name: string;
    description: string;
    tech: string[];
    url?: string;
    github?: string;
    featured: boolean;
  }>;

  export const posts: Array<{
    slug: string;
    title: string;
    date: string;
    description: string;
    featured?: boolean;
  }>;
}
